name: Deploy to BigRock

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy over SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}

          use_insecure_cipher: true
          cipher: aes128-ctr,aes192-ctr,aes256-ctr
          timeout: 60s
          command_timeout: 10m

          script: |
            cd /home4/khatijil/public_html/myadmissionadvisor

            git fetch origin
            git reset --hard origin/main

            find . -type d -exec chmod 755 {} \;
            find . -type f -exec chmod 644 {} \;

            echo "Deployment completed."
